### ISSUE TITLE
[Question] Do not transpile `component-a`

### ISSUE THREAD

**Issue by sebald** [deptno/typescript-monorepo-next-example#1]
Hey there!

Thank you so much for this example! 👏 I have a question regarding the compilation of the `component-a` package. I would like to not commit the compiled JS output into the repo. Is it possible to use the TS files directly?

I updated `next` to v7 and removed the compiled files (`.js`, ...), but I get the following error:

```
../component-a/index.tsx 3:23
Module parse failed: Unexpected token (3:23)
You may need an appropriate loader to handle this file type.
| import * as React from 'react'
| 
> export const ComponentA: React.SFC<{}> = props =>
|   <div>ComponentA</div>
|
```

Is it possible to configure `babel`/`webpack` such that the TS files are compiled on the fly?

**Comment by LancelotP** [comment]
Hello @sebald !

I'm facing the exact same issue and can't find a proper solution to let next compile itself the `component-a`.

However I ended up with solution that suits me for the moment, which is :

```json
# package/components-a/package.json
...
"module": "dist/index.js",
"typings": "dist/index.d.ts",
...
```

You need to build the component-a before running the app, and after that you have complete type support inside your IDE and the app works wonders.

It is not perfect and I'll keep searching to improve this

**Comment by deptno** [comment]
@sebald Hi.

I understand it is main painful point related with Monorepo - TypeScript combination, but

**`.js` must be needed for module.**

each packages recognize package as **external package** each other.
and `component-a` is a **external** package.

external package must have entry **javascript** file described in `package.json`'s `main` property.
